services:
  pdf-rag-app:
    image: seongmin602/pdf-rag-app:0.1
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      #- OPENAI_API_KEY=${{OPENAI_API_KEY }}
    env_file:
      - .env
    volumes:
      # PDF 업로드 파일을 호스트에 저장
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s